Release/8.10.4 - Policy numbering
waynestate/base-site pull request #719
Opened 2024-06-21 19:45 UTC by AmbyrElan

Releasing the policy numbering style changes to base.

2024-06-22 10:20 UTC, nickdenardis commented
I'm good with this release after there is a write-up of the changes. 

Can you outline the items part of this release in two categories?

1. End-user/template changes/additions
2. Structural changes for developers to know

2024-06-22 10:20 UTC, nickdenardis approved these changes

2024-06-25 02:55 UTC, breakdancingcat approved these changes

2024-06-25 03:00 UTC, breakdancingcat commented on styleguide/Views/styleguide-cms-list-styles.blade.php
> +                <li>&#20;&#20;&#20;&#20;&lt;li&gt;Item 1.0&lt;/li&gt;</li>
Shouldn't all these be added by css?

2024-06-25 09:29 UTC, nickdenardis requested changes
A few inline comments in addition to the need for a write up of the changes in this release since it appears to be more than only policy numbering addition.

2024-06-25 09:29 UTC, nickdenardis commented on resources/scss/components/_flag.scss
> +                /*
Let's remove this commented-out style.

2024-06-25 09:29 UTC, nickdenardis commented on resources/views/components/accordion.blade.php
> +                            <img src="{{ $item['relative_url'] }}" alt="{{ $item['filename_alt_text'] }}">
What is the guidelines we are following for lazy loading images? Anything beyond the hero?

2024-06-25 09:29 UTC, nickdenardis commented on resources/views/homepage.blade.php
> +            @include('components.catalog', ['data' => $components['catalog-1']['data'], 'component' => $components['catalog-1']['component'], 'class' => 'my-class'])
What is `my-class` here?

2024-07-24 14:32 UTC, breakdancingcat commented
I believe these are incomplete pieces that I left behind, I will close this out and create a new release with the latest changes

2024-07-24 14:32 UTC, closed without merging